# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug32
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug32)
  2gis_test_work_config = debug32

else ifeq ($(config),release32)
  2gis_test_work_config = release32

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := 2gis_test_work

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

2gis_test_work:
ifneq (,$(2gis_test_work_config))
	@echo "==== Building 2gis_test_work ($(2gis_test_work_config)) ===="
	@${MAKE} --no-print-directory -C build -f Makefile config=$(2gis_test_work_config)
endif

clean:
	@${MAKE} --no-print-directory -C build -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug32"
	@echo "  release32"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   2gis_test_work"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"